// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraBond is the `eraBond` instruction.
type EraBond struct {

	// [0] = [WRITE, SIGNER] feeAndRentPayer
	//
	// [1] = [WRITE] stakeManager
	//
	// [2] = [] stakingTokenMint
	//
	// [3] = [WRITE] stakeManagerStakingTokenAccount
	//
	// [4] = [WRITE] stakingPool
	//
	// [5] = [WRITE] stakingPoolStakingTokenAccount
	//
	// [6] = [WRITE] stakingStakeAccount
	//
	// [7] = [] stakingProgram
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] associatedTokenProgram
	//
	// [10] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraBondInstructionBuilder creates a new `EraBond` instruction builder.
func NewEraBondInstructionBuilder() *EraBond {
	nd := &EraBond{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetFeeAndRentPayerAccount sets the "feeAndRentPayer" account.
func (inst *EraBond) SetFeeAndRentPayerAccount(feeAndRentPayer ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(feeAndRentPayer).WRITE().SIGNER()
	return inst
}

// GetFeeAndRentPayerAccount gets the "feeAndRentPayer" account.
func (inst *EraBond) GetFeeAndRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraBond) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraBond) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakingTokenMintAccount sets the "stakingTokenMint" account.
func (inst *EraBond) SetStakingTokenMintAccount(stakingTokenMint ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakingTokenMint)
	return inst
}

// GetStakingTokenMintAccount gets the "stakingTokenMint" account.
func (inst *EraBond) GetStakingTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakeManagerStakingTokenAccountAccount sets the "stakeManagerStakingTokenAccount" account.
func (inst *EraBond) SetStakeManagerStakingTokenAccountAccount(stakeManagerStakingTokenAccount ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakeManagerStakingTokenAccount).WRITE()
	return inst
}

// GetStakeManagerStakingTokenAccountAccount gets the "stakeManagerStakingTokenAccount" account.
func (inst *EraBond) GetStakeManagerStakingTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *EraBond) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *EraBond) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakingPoolStakingTokenAccountAccount sets the "stakingPoolStakingTokenAccount" account.
func (inst *EraBond) SetStakingPoolStakingTokenAccountAccount(stakingPoolStakingTokenAccount ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(stakingPoolStakingTokenAccount).WRITE()
	return inst
}

// GetStakingPoolStakingTokenAccountAccount gets the "stakingPoolStakingTokenAccount" account.
func (inst *EraBond) GetStakingPoolStakingTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakingStakeAccountAccount sets the "stakingStakeAccount" account.
func (inst *EraBond) SetStakingStakeAccountAccount(stakingStakeAccount ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakingStakeAccount).WRITE()
	return inst
}

// GetStakingStakeAccountAccount gets the "stakingStakeAccount" account.
func (inst *EraBond) GetStakingStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakingProgramAccount sets the "stakingProgram" account.
func (inst *EraBond) SetStakingProgramAccount(stakingProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakingProgram)
	return inst
}

// GetStakingProgramAccount gets the "stakingProgram" account.
func (inst *EraBond) GetStakingProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *EraBond) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *EraBond) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *EraBond) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *EraBond) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EraBond) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EraBond) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst EraBond) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraBond,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraBond) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraBond) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.FeeAndRentPayer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakingTokenMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakeManagerStakingTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.StakingPoolStakingTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakingStakeAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakingProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EraBond) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraBond")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         feeAndRentPayer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            stakeManager", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        stakingTokenMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("stakeManagerStakingToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             stakingPool", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" stakingPoolStakingToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("            stakingStake", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          stakingProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("            tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  associatedTokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           systemProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj EraBond) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraBond) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraBondInstruction declares a new EraBond instruction with the provided parameters and accounts.
func NewEraBondInstruction(
	// Accounts:
	feeAndRentPayer ag_solanago.PublicKey,
	stakeManager ag_solanago.PublicKey,
	stakingTokenMint ag_solanago.PublicKey,
	stakeManagerStakingTokenAccount ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey,
	stakingPoolStakingTokenAccount ag_solanago.PublicKey,
	stakingStakeAccount ag_solanago.PublicKey,
	stakingProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EraBond {
	return NewEraBondInstructionBuilder().
		SetFeeAndRentPayerAccount(feeAndRentPayer).
		SetStakeManagerAccount(stakeManager).
		SetStakingTokenMintAccount(stakingTokenMint).
		SetStakeManagerStakingTokenAccountAccount(stakeManagerStakingTokenAccount).
		SetStakingPoolAccount(stakingPool).
		SetStakingPoolStakingTokenAccountAccount(stakingPoolStakingTokenAccount).
		SetStakingStakeAccountAccount(stakingStakeAccount).
		SetStakingProgramAccount(stakingProgram).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
