// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Stake is the `stake` instruction.
type Stake struct {
	StakeAmount *uint64

	// [0] = [SIGNER] user
	//
	// [1] = [WRITE, SIGNER] rentPayer
	//
	// [2] = [WRITE] stakeManager
	//
	// [3] = [WRITE] lsdTokenMint
	//
	// [4] = [] stakingTokenMint
	//
	// [5] = [WRITE] userLsdTokenAccount
	//
	// [6] = [WRITE] userStakingTokenAccount
	//
	// [7] = [WRITE] stakeManagerStakingTokenAccount
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] associatedTokenProgram
	//
	// [10] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakeInstructionBuilder creates a new `Stake` instruction builder.
func NewStakeInstructionBuilder() *Stake {
	nd := &Stake{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetStakeAmount sets the "stakeAmount" parameter.
func (inst *Stake) SetStakeAmount(stakeAmount uint64) *Stake {
	inst.StakeAmount = &stakeAmount
	return inst
}

// SetUserAccount sets the "user" account.
func (inst *Stake) SetUserAccount(user ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(user).SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *Stake) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *Stake) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *Stake) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *Stake) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *Stake) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *Stake) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *Stake) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetStakingTokenMintAccount sets the "stakingTokenMint" account.
func (inst *Stake) SetStakingTokenMintAccount(stakingTokenMint ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(stakingTokenMint)
	return inst
}

// GetStakingTokenMintAccount gets the "stakingTokenMint" account.
func (inst *Stake) GetStakingTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserLsdTokenAccountAccount sets the "userLsdTokenAccount" account.
func (inst *Stake) SetUserLsdTokenAccountAccount(userLsdTokenAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userLsdTokenAccount).WRITE()
	return inst
}

// GetUserLsdTokenAccountAccount gets the "userLsdTokenAccount" account.
func (inst *Stake) GetUserLsdTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetUserStakingTokenAccountAccount sets the "userStakingTokenAccount" account.
func (inst *Stake) SetUserStakingTokenAccountAccount(userStakingTokenAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(userStakingTokenAccount).WRITE()
	return inst
}

// GetUserStakingTokenAccountAccount gets the "userStakingTokenAccount" account.
func (inst *Stake) GetUserStakingTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakeManagerStakingTokenAccountAccount sets the "stakeManagerStakingTokenAccount" account.
func (inst *Stake) SetStakeManagerStakingTokenAccountAccount(stakeManagerStakingTokenAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakeManagerStakingTokenAccount).WRITE()
	return inst
}

// GetStakeManagerStakingTokenAccountAccount gets the "stakeManagerStakingTokenAccount" account.
func (inst *Stake) GetStakeManagerStakingTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Stake) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Stake) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *Stake) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *Stake) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Stake) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Stake) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst Stake) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Stake,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Stake) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Stake) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeAmount == nil {
			return errors.New("StakeAmount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.StakingTokenMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserLsdTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.UserStakingTokenAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakeManagerStakingTokenAccount is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *Stake) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Stake")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeAmount", *inst.StakeAmount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                    user", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("               rentPayer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            stakeManager", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("            lsdTokenMint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        stakingTokenMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("            userLsdToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        userStakingToken", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("stakeManagerStakingToken", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("            tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  associatedTokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           systemProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj Stake) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeAmount` param:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Stake) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}

// NewStakeInstruction declares a new Stake instruction with the provided parameters and accounts.
func NewStakeInstruction(
	// Parameters:
	stakeAmount uint64,
	// Accounts:
	user ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	stakeManager ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	stakingTokenMint ag_solanago.PublicKey,
	userLsdTokenAccount ag_solanago.PublicKey,
	userStakingTokenAccount ag_solanago.PublicKey,
	stakeManagerStakingTokenAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *Stake {
	return NewStakeInstructionBuilder().
		SetStakeAmount(stakeAmount).
		SetUserAccount(user).
		SetRentPayerAccount(rentPayer).
		SetStakeManagerAccount(stakeManager).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetStakingTokenMintAccount(stakingTokenMint).
		SetUserLsdTokenAccountAccount(userLsdTokenAccount).
		SetUserStakingTokenAccountAccount(userStakingTokenAccount).
		SetStakeManagerStakingTokenAccountAccount(stakeManagerStakingTokenAccount).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
