// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferStakeManagerAdmin is the `transferStakeManagerAdmin` instruction.
type TransferStakeManagerAdmin struct {
	NewAdmin *ag_solanago.PublicKey

	// [0] = [SIGNER] admin
	//
	// [1] = [WRITE] stakeManager
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferStakeManagerAdminInstructionBuilder creates a new `TransferStakeManagerAdmin` instruction builder.
func NewTransferStakeManagerAdminInstructionBuilder() *TransferStakeManagerAdmin {
	nd := &TransferStakeManagerAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewAdmin sets the "newAdmin" parameter.
func (inst *TransferStakeManagerAdmin) SetNewAdmin(newAdmin ag_solanago.PublicKey) *TransferStakeManagerAdmin {
	inst.NewAdmin = &newAdmin
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *TransferStakeManagerAdmin) SetAdminAccount(admin ag_solanago.PublicKey) *TransferStakeManagerAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *TransferStakeManagerAdmin) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *TransferStakeManagerAdmin) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *TransferStakeManagerAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *TransferStakeManagerAdmin) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst TransferStakeManagerAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferStakeManagerAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferStakeManagerAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferStakeManagerAdmin) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewAdmin == nil {
			return errors.New("NewAdmin parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
	}
	return nil
}

func (inst *TransferStakeManagerAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferStakeManagerAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewAdmin", *inst.NewAdmin))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj TransferStakeManagerAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewAdmin` param:
	err = encoder.Encode(obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferStakeManagerAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewAdmin`:
	err = decoder.Decode(&obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferStakeManagerAdminInstruction declares a new TransferStakeManagerAdmin instruction with the provided parameters and accounts.
func NewTransferStakeManagerAdminInstruction(
	// Parameters:
	newAdmin ag_solanago.PublicKey,
	// Accounts:
	admin ag_solanago.PublicKey,
	stakeManager ag_solanago.PublicKey) *TransferStakeManagerAdmin {
	return NewTransferStakeManagerAdminInstructionBuilder().
		SetNewAdmin(newAdmin).
		SetAdminAccount(admin).
		SetStakeManagerAccount(stakeManager)
}
