// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package staking_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AcceptAdmin is the `acceptAdmin` instruction.
type AcceptAdmin struct {

	// [0] = [SIGNER] pendingAdmin
	//
	// [1] = [WRITE] stakingPool
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAcceptAdminInstructionBuilder creates a new `AcceptAdmin` instruction builder.
func NewAcceptAdminInstructionBuilder() *AcceptAdmin {
	nd := &AcceptAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetPendingAdminAccount sets the "pendingAdmin" account.
func (inst *AcceptAdmin) SetPendingAdminAccount(pendingAdmin ag_solanago.PublicKey) *AcceptAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(pendingAdmin).SIGNER()
	return inst
}

// GetPendingAdminAccount gets the "pendingAdmin" account.
func (inst *AcceptAdmin) GetPendingAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *AcceptAdmin) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *AcceptAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *AcceptAdmin) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst AcceptAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AcceptAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AcceptAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AcceptAdmin) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.PendingAdmin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
	}
	return nil
}

func (inst *AcceptAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AcceptAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("pendingAdmin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" stakingPool", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj AcceptAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *AcceptAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewAcceptAdminInstruction declares a new AcceptAdmin instruction with the provided parameters and accounts.
func NewAcceptAdminInstruction(
	// Accounts:
	pendingAdmin ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey) *AcceptAdmin {
	return NewAcceptAdminInstructionBuilder().
		SetPendingAdminAccount(pendingAdmin).
		SetStakingPoolAccount(stakingPool)
}
