// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package staking_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Config is the `config` instruction.
type Config struct {
	Params *ConfigParams

	// [0] = [SIGNER] admin
	//
	// [1] = [WRITE] stakingPool
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewConfigInstructionBuilder creates a new `Config` instruction builder.
func NewConfigInstructionBuilder() *Config {
	nd := &Config{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *Config) SetParams(params ConfigParams) *Config {
	inst.Params = &params
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *Config) SetAdminAccount(admin ag_solanago.PublicKey) *Config {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *Config) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *Config) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *Config {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *Config) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst Config) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Config,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Config) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Config) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
	}
	return nil
}

func (inst *Config) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Config")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("stakingPool", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj Config) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Config) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewConfigInstruction declares a new Config instruction with the provided parameters and accounts.
func NewConfigInstruction(
	// Parameters:
	params ConfigParams,
	// Accounts:
	admin ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey) *Config {
	return NewConfigInstructionBuilder().
		SetParams(params).
		SetAdminAccount(admin).
		SetStakingPoolAccount(stakingPool)
}
