// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package staking_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeStakingPool is the `initializeStakingPool` instruction.
type InitializeStakingPool struct {
	Params *InitializeStakingPoolParams

	// [0] = [SIGNER] admin
	//
	// [1] = [WRITE, SIGNER] rentPayer
	//
	// [2] = [] tokenMint
	//
	// [3] = [WRITE] stakingPool
	//
	// [4] = [WRITE] adminTokenAccount
	//
	// [5] = [WRITE] poolTokenAccount
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] associatedTokenProgram
	//
	// [8] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeStakingPoolInstructionBuilder creates a new `InitializeStakingPool` instruction builder.
func NewInitializeStakingPoolInstructionBuilder() *InitializeStakingPool {
	nd := &InitializeStakingPool{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 9),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *InitializeStakingPool) SetParams(params InitializeStakingPoolParams) *InitializeStakingPool {
	inst.Params = &params
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *InitializeStakingPool) SetAdminAccount(admin ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *InitializeStakingPool) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *InitializeStakingPool) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *InitializeStakingPool) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenMintAccount sets the "tokenMint" account.
func (inst *InitializeStakingPool) SetTokenMintAccount(tokenMint ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenMint)
	return inst
}

// GetTokenMintAccount gets the "tokenMint" account.
func (inst *InitializeStakingPool) GetTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *InitializeStakingPool) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *InitializeStakingPool) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetAdminTokenAccountAccount sets the "adminTokenAccount" account.
func (inst *InitializeStakingPool) SetAdminTokenAccountAccount(adminTokenAccount ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(adminTokenAccount).WRITE()
	return inst
}

// GetAdminTokenAccountAccount gets the "adminTokenAccount" account.
func (inst *InitializeStakingPool) GetAdminTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPoolTokenAccountAccount sets the "poolTokenAccount" account.
func (inst *InitializeStakingPool) SetPoolTokenAccountAccount(poolTokenAccount ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(poolTokenAccount).WRITE()
	return inst
}

// GetPoolTokenAccountAccount gets the "poolTokenAccount" account.
func (inst *InitializeStakingPool) GetPoolTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *InitializeStakingPool) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *InitializeStakingPool) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *InitializeStakingPool) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *InitializeStakingPool) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeStakingPool) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeStakingPool {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeStakingPool) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

func (inst InitializeStakingPool) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeStakingPool,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeStakingPool) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeStakingPool) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.AdminTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.PoolTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *InitializeStakingPool) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeStakingPool")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=9]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             rentPayer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("             tokenMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("           stakingPool", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("            adminToken", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("             poolToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(8)))
					})
				})
		})
}

func (obj InitializeStakingPool) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitializeStakingPool) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewInitializeStakingPoolInstruction declares a new InitializeStakingPool instruction with the provided parameters and accounts.
func NewInitializeStakingPoolInstruction(
	// Parameters:
	params InitializeStakingPoolParams,
	// Accounts:
	admin ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	tokenMint ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey,
	adminTokenAccount ag_solanago.PublicKey,
	poolTokenAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *InitializeStakingPool {
	return NewInitializeStakingPoolInstructionBuilder().
		SetParams(params).
		SetAdminAccount(admin).
		SetRentPayerAccount(rentPayer).
		SetTokenMintAccount(tokenMint).
		SetStakingPoolAccount(stakingPool).
		SetAdminTokenAccountAccount(adminTokenAccount).
		SetPoolTokenAccountAccount(poolTokenAccount).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
