// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package staking_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Stake is the `stake` instruction.
type Stake struct {
	StakeAmount *uint64

	// [0] = [SIGNER] user
	//
	// [1] = [WRITE, SIGNER] rentPayer
	//
	// [2] = [WRITE] stakingPool
	//
	// [3] = [] tokenMint
	//
	// [4] = [WRITE] userTokenAccount
	//
	// [5] = [WRITE] poolTokenAccount
	//
	// [6] = [WRITE] stakeAccount
	//
	// [7] = [] tokenProgram
	//
	// [8] = [] associatedTokenProgram
	//
	// [9] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakeInstructionBuilder creates a new `Stake` instruction builder.
func NewStakeInstructionBuilder() *Stake {
	nd := &Stake{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetStakeAmount sets the "stakeAmount" parameter.
func (inst *Stake) SetStakeAmount(stakeAmount uint64) *Stake {
	inst.StakeAmount = &stakeAmount
	return inst
}

// SetUserAccount sets the "user" account.
func (inst *Stake) SetUserAccount(user ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(user).SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *Stake) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *Stake) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *Stake) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *Stake) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *Stake) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetTokenMintAccount sets the "tokenMint" account.
func (inst *Stake) SetTokenMintAccount(tokenMint ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(tokenMint)
	return inst
}

// GetTokenMintAccount gets the "tokenMint" account.
func (inst *Stake) GetTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserTokenAccountAccount sets the "userTokenAccount" account.
func (inst *Stake) SetUserTokenAccountAccount(userTokenAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userTokenAccount).WRITE()
	return inst
}

// GetUserTokenAccountAccount gets the "userTokenAccount" account.
func (inst *Stake) GetUserTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPoolTokenAccountAccount sets the "poolTokenAccount" account.
func (inst *Stake) SetPoolTokenAccountAccount(poolTokenAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(poolTokenAccount).WRITE()
	return inst
}

// GetPoolTokenAccountAccount gets the "poolTokenAccount" account.
func (inst *Stake) GetPoolTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *Stake) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakeAccount).WRITE()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *Stake) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Stake) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Stake) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *Stake) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *Stake) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Stake) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Stake) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst Stake) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Stake,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Stake) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Stake) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeAmount == nil {
			return errors.New("StakeAmount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.TokenMint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.PoolTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *Stake) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Stake")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeAmount", *inst.StakeAmount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                  user", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             rentPayer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("           stakingPool", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             tokenMint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             userToken", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("             poolToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                 stake", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj Stake) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeAmount` param:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Stake) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}

// NewStakeInstruction declares a new Stake instruction with the provided parameters and accounts.
func NewStakeInstruction(
	// Parameters:
	stakeAmount uint64,
	// Accounts:
	user ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey,
	tokenMint ag_solanago.PublicKey,
	userTokenAccount ag_solanago.PublicKey,
	poolTokenAccount ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *Stake {
	return NewStakeInstructionBuilder().
		SetStakeAmount(stakeAmount).
		SetUserAccount(user).
		SetRentPayerAccount(rentPayer).
		SetStakingPoolAccount(stakingPool).
		SetTokenMintAccount(tokenMint).
		SetUserTokenAccountAccount(userTokenAccount).
		SetPoolTokenAccountAccount(poolTokenAccount).
		SetStakeAccountAccount(stakeAccount).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
