// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package staking_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferAdmin is the `transferAdmin` instruction.
type TransferAdmin struct {
	NewAdmin *ag_solanago.PublicKey

	// [0] = [SIGNER] admin
	//
	// [1] = [WRITE] stakingPool
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferAdminInstructionBuilder creates a new `TransferAdmin` instruction builder.
func NewTransferAdminInstructionBuilder() *TransferAdmin {
	nd := &TransferAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewAdmin sets the "newAdmin" parameter.
func (inst *TransferAdmin) SetNewAdmin(newAdmin ag_solanago.PublicKey) *TransferAdmin {
	inst.NewAdmin = &newAdmin
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *TransferAdmin) SetAdminAccount(admin ag_solanago.PublicKey) *TransferAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *TransferAdmin) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakingPoolAccount sets the "stakingPool" account.
func (inst *TransferAdmin) SetStakingPoolAccount(stakingPool ag_solanago.PublicKey) *TransferAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakingPool).WRITE()
	return inst
}

// GetStakingPoolAccount gets the "stakingPool" account.
func (inst *TransferAdmin) GetStakingPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst TransferAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferAdmin) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewAdmin == nil {
			return errors.New("NewAdmin parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakingPool is not set")
		}
	}
	return nil
}

func (inst *TransferAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewAdmin", *inst.NewAdmin))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("stakingPool", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj TransferAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewAdmin` param:
	err = encoder.Encode(obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewAdmin`:
	err = decoder.Decode(&obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferAdminInstruction declares a new TransferAdmin instruction with the provided parameters and accounts.
func NewTransferAdminInstruction(
	// Parameters:
	newAdmin ag_solanago.PublicKey,
	// Accounts:
	admin ag_solanago.PublicKey,
	stakingPool ag_solanago.PublicKey) *TransferAdmin {
	return NewTransferAdminInstructionBuilder().
		SetNewAdmin(newAdmin).
		SetAdminAccount(admin).
		SetStakingPoolAccount(stakingPool)
}
