RpcEndpoint = "https://api.devnet.solana.com"
# RpcEndpoint = "https://api.testnet.sonic.game"
LogFileDir = ""
KeystorePath = "./keys/solana_keys.json"

StakeManagerAddress = "9MD8swVgHG11rmAhrD2ipgfqvUbiJBHL148pHrg1WRKK"

FeePayerAccount = "ErCsmTQhM9qt17ce8XDTasKo76FEdg2scP2UX4VLxKDb"
