RpcEndpoint = "https://api.devnet.solana.com"
KeystorePath = "./keys/solana_keys.json"

LsdProgramID = "CEftts4KkpMPiJg9hccAgqZHvUc3t1hx9VssMUGkX3ec"
StakeManagerAddress = "921ksHLP7Hc4tENgziqz4xZFCiwzzuii6HEwUm9EnB1H"

FeePayerAccount = "ErCsmTQhM9qt17ce8XDTasKo76FEdg2scP2UX4VLxKDb"
AdminAccount = "GgAy6GnqaPJUdGfCQGMgW2fGMMvmxc3E7a2oizFuCbhF"

# Metadata parameters
TokenName = "Liquid Staking Token"
TokenSymbol = "LST"
TokenUri = "https://your-metadata-uri.com/token.json" 